### ISSUE TITLE
First launch issue

### ISSUE THREAD

**Issue by ThatOneBepis** [jakubDoka/go-tanks#1]
"*computerName*\AppData\Roaming/go-tanks/config.json: The system cannot find the file specified." is found within the debug menu
and the screen appears black

**Comment by jakubDoka** [comment]
what is your operating system?

**Comment by ThatOneBepis** [comment]
Windows 10

**Comment by jakubDoka** [comment]
For now this error will appear no matter what, if it annoys you too match you can create the file in your app data and it will dissapear. Reason is that there is nothing to configure yet. When ui color option will be added, this will also change. Settings will then also work.

**Comment by ThatOneBepis** [comment]
Alright, thanks
